# Generated by Django 4.2.6 on 2023-11-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
