# Generated by Django 4.2.6 on 2023-11-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_is_published', 'Can publish product'), ('set_category', 'Can change category'), ('set_description', 'Can change description')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
